### ISSUE TITLE
[Bug] Couldn't read component "minecraft:consumable"

### ISSUE THREAD

**Issue by zndrmn** [boyonk913/item-components#10]
This causes one of the example packs [Edible Sugar](https://github.com/boyonk913/item-components/tree/master/datapacks/edible_sugar/data/edible_sugar) to not function at all and just gives an error in the logs

```log
[20:32:41] [Render thread/ERROR]: Couldn't read components rebalanced_foods:berries from rebalanced_foods:item_components/berries.json in data pack file/Rebalanced Foods
com.google.gson.JsonSyntaxException: No component with type: 'minecraft:consumable'; No component with type: 'minecraft:consumable' missed input: {"minecraft:consumable":{"consume_seconds":0.8}}
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at com.boyonk.itemcomponents.ItemComponentsManager.loadIntoMap(ItemComponentsManager.java:100) ~[item-components-1.1+1.21.jar:?]
	at com.boyonk.itemcomponents.ItemComponentsManager.method_14491(ItemComponentsManager.java:64) ~[item-components-1.1+1.21.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_45694(class_7196.java:182) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_54610(class_7196.java:137) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_57780(class_7196.java:323) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_57781(class_7196.java:313) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_57782(class_7196.java:278) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_57784(class_7196.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_8496.method_51261(class_8496.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.mdf994f8$continue$lambda$drawMenuButton$0$2(class_442.java:2542) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25402(class_442.java:295) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) [lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) [client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:303) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1307) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
```

**Comment by Minecrafthyr** [comment]
Consumeable component does not exist before Minecraft 1.21.2.
